---
name: "Java + Maven"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    timeout-minutes: 360
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    strategy:
      fail-fast: false
      matrix:
        language:
        - "java"
        java-version:
        - "21"
        - "23"
        distribution:
        - "zulu"
        - "temurin"
        - "semeru"
        - "graalvm"
    steps:
    - uses: "actions/checkout@v5"
    - name: "Set up JDK ${{ matrix.java-version }}-${{ matrix.distribution }}"
      uses: "actions/setup-java@v5"
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java-version }}"
        java-package: "jdk"
        cache: "maven"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.10"
    - name: "Initialize CodeQL"
      uses: "github/codeql-action/init@v4"
      with:
        languages: "${{ matrix.language }}"
    - run: "mvn -s settings.xml spotless:check install -Djava.version=${{ matrix.java-version\
        \ }}"
    - name: "Perform CodeQL Analysis"
      uses: "github/codeql-action/analyze@v4"
    - name: "Submit Dependency Snapshot"
      uses: "advanced-security/maven-dependency-submission-action@v5"
      with:
        token: "${{ secrets.GH_TOKEN }}"
        maven-args: "-s settings.xml"
